### ISSUE TITLE
Error: unauthorized_client

### ISSUE THREAD

**Issue by yassin-mokni** [burawi/youtup#1]
I followed the code example but I am getting an `xoauth2` error :
```javascript
Error: unauthorized_client
    at /project/node_modules/xoauth2/src/xoauth2.js:160:29
    at cleanupAndCallback (/project/node_modules/xoauth2/src/xoauth2.js:222:18)
    at IncomingMessage.<anonymous> (/project/node_modules/xoauth2/src/xoauth2.js:236:20)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by harvinder-ss** [comment]
@yassinMk  did you find any solution for it? As I am getting the same issue

**Comment by rtwalz** [comment]
Yes this module is broken. Don't even try installing it, waste of time
